### PR TITLE
Periodically restream queue

### PR DESCRIPTION
**Pull request by nzey**
Periodically restream queue. 

# TODO
- [ ] Set task to run from the dashboard, here: https://cl.ly/efde17f42035

### CODE REVIEW

**Comment by thebrettd** [comment]
This is interesting - have you seen Heroku Scheduler? https://devcenter.heroku.com/articles/scheduler

I wonder if it is any cheaper/better to use those instead of always having a dyno running that is usually does nothing.

**Comment by nzey** [comment]
Oh yeh, @thebrettd, that looks perfect.

**Review by mrubens — APPROVED** [review]

**Comment by nzey** [comment]
@mrubens 10 min, hourly and daily are the only scheduling options with the add-on. Will hourly be okay?  For more flexibility, we could use this: https://devcenter.heroku.com/articles/clock-processes-python

**Comment by mrubens** [comment]
I might try 10m

**Comment by mrubens** [comment]
Er, maybe hourly is safer.

**Pull request merged**
